# This builds and deploys ISLP docs

name: Build docs

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      LABS:
        description: 'Labs version'
        required: true
        default: 'v2'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install
      - name: Install dependencies 
        run: |
          sudo apt-get install r-base
          pip install -r requirements.txt
          pip install -r docs/requirements.txt
          pip install .

      # Checkout labs
      - name: Checkout version of labs
        env:
          LABS:  ${{ inputs.LABS }}
        run: |
          git submodule update --init --force docs/ISLP_labs
          cd docs
          python fix_and_clear_notebooks.py --version $LABS         
          rm source/labs/Ch*md

      - name: Make docs
        run: |
          cd docs
          make html

      # Store the output
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: ISLP_docs
          path: docs/build/html
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@master
      with:
        name: ISLP_docs
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main